apiVersion: v1
kind: Service
metadata:
  name: gitlab-repo-creator-svc
spec:
  selector:
    app: gitlab-repo-creator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
  type: NodePort
